### ISSUE TITLE
Some errors in compilation/execution don't appear in the CLI output

### ISSUE THREAD

**Issue by afidegnum** [arctic-hen7/perseus#74] opened 2021-11-11 08:38 UTC
**Describe the bug**
I ran cargo check, everything works well with no error but when I ran `persus serve` the servers compiles then exits 

this is the current state from the shell 

 Finished dev [unoptimized + debuginfo] target(s) in 29.30s
     Running `target/debug/perseus-builder`
  [1/4] 🔨 Generating your app...❌
  [2/4] 🏗️  Building your app to Wasm...✅
  [3/4] 📡 Building server...✅

**Expected behavior**
Is there a way to print the error log? 

**Environment (please complete the following information):**
```
[package]
name = "emlfront"
version = "0.3.0-beta.3"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
perseus = "0.3.0-beta.17"
sycamore = "0.6.3"
sycamore-router = "0.6.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
fluent-bundle = "0.15"
walkdir = "2"
pulldown-cmark = "0.8"
lazy_static = "1"
web-sys = { version = "0.3", features = [ "Event", "EventTarget" ] }
wasm-bindgen = "0.2"
perseus-size-opt = "0.1"

# [lib]
# crate-type = ["cdylib", "rlib"]
```

**Comment by arctic-hen7** [comment] 2021-11-11 08:46
Ah. This can occasionally happen, and should be listed in the docs (and further investigated generally). You should be able to view the error logs by moving into the `.perseus/builder` directory and running `cargo run --bin perseus-builder`. That will run the binary used for building your app directly. Also, it looks like you're using a very old beta, the latest is beta 17 (very soon to be 18).

**Comment by arctic-hen7** [comment] 2021-11-11 08:47
I'll leave this issue open until I've sorted this problem out more broadly, because it can be very cryptic!

**Comment by afidegnum** [comment] 2021-11-11 09:39
ok, I've found one of the culprits, taken from your `website` example, Perseus had   `features = [ "translator-fluent" ] ` even though I disabled it, the function perseus::t and link was still in the code. which generated that error, I wish it should have more explicit errors especially calling functions when its feature is not active.

**Comment by arctic-hen7** [comment] 2021-11-13 00:48
Okay, I know I've had this issue before, but now that I'm trying to cause it, I'm having trouble! @afidegnum, could you describe exactly (step-by-step) how to generate this bug from one of the examples? I have a good idea of what the problem is, but I need to check if my solution has actually worked.

**Comment by afidegnum** [comment] 2021-11-13 09:45
ok, let me try to replicate the bug from my end again. but here is the workflow: 
add perseus into the cargo without the fluent feature activated. `perseus = "0.3.0-beta.17"` then in calling either `link` or `t`
`use perseus::{link, t;` is enough to generate the error. I will check again on the latest commit and see

**Comment by arctic-hen7** [comment] 2021-11-28 05:31
As a side note, I've added `perseus snoop` now, which allows you to inspect the logs from building, Wasm building, and server running automatically. That doesn't fix this issue, but the latest code should (which will be released in beta 18).

**Comment by afidegnum** [comment] 2021-11-28 07:41
Thanks a lot, i'm going to make a good use of it

**Comment by arctic-hen7** [comment] 2021-12-02 01:01
@afidegnum I've released beta 18, does this issue still apply to you? Otherwise, I'll close it.

**Comment by afidegnum** [comment] 2021-12-02 02:13
Thanks, don't close it yet, currently working on sycamore, will come back to Perseus before the end of the day.

**Comment by arctic-hen7** [comment] 2021-12-04 05:28
@afidegnum any progress on this yet?

**Comment by afidegnum** [comment] 2021-12-04 10:02
yes, there is still work in the background, I'm working on the backend with sycamore and will bridge with Perseus. I was also working with some API stuffs too... I will update you shortly

**Comment by arctic-hen7** [comment] 2021-12-07 06:57
Okay, I've encountered another manifestation of this bug, so I'll keep this open for now and do some more testing.

**Comment by arctic-hen7** [comment] 2021-12-30 03:36
Okay, this doesn't seem to be an issue anymore, so I'm tentatively closing this. If anyone experiences this issue again, please let me know with an MRE, because getting this bug to happen is quite difficult when you're trying!

**Closed by arctic-hen7** 2021-12-30 03:36 UTC
Labels: C-bug, A-cli, D-medium, P-high, S-waiting-on-author
