### ISSUE TITLE
<!--#--> in web title when translation string is used

### ISSUE THREAD

**Issue by adundovi** [arctic-hen7/perseus#105] opened 2022-01-04 15:26 UTC
**Describe the bug**
Recently, a regression is introduced when displaying a head title. It occurs when the translation marco `t!()` is used within the head title tag of a page and instead of displaying only a translated string, comment tags are inserted, thus, the final translated string is displayed in a browser as `<!--#-->translated string<!--/-->`.

I don't know is it due to `sycamore` or `perseus` but since it occurs when `t!` macro is used, I report it here. When an ordinary string variable is used, everything is fine.

**To Reproduce**

One can use the i18n example, and add the head function with the title:
```rust
pub fn get_template<G: Html>() -> Template<G> {
    Template::new("about")
        .template(about_page)
        .head(head)
}

#[perseus::head]
pub fn head() -> View<SsrNode> {
    view! {
         title { (t!("about")) }
    }
}

```

**Expected behavior**
A translated string is displayed without comment tags.

**Environment (please complete the following information):**
 - Perseus Version: 0.3.1
 - Sycamore Version: 0.7
 - OS: GNU/Linux
 - Browser: Firefox
 - Browser Version: 95

**Comment by arctic-hen7** [comment] 2022-01-04 20:18
Does this still occur if you remove the `hydrate` feature flag?

**Comment by adundovi** [comment] 2022-01-04 21:07
Both, with `hydrate` and without `hydrate`, I reproduce the problem and I performed `perseus clean` before teting.

**Comment by arctic-hen7** [comment] 2022-01-04 21:51
Hmm okay. I'll get on this!

**Comment by arctic-hen7** [comment] 2022-01-05 20:28
Even after running `perseus clean`, that reproduction in the i18n example (also removing the `<title>` element from `index.html`), doesn't produce this bug for me on Firefox 96.0b10 running on Ubuntu. Maybe there's something else going on here, could you post a self-contained MRE?

**Comment by arctic-hen7** [comment] 2022-01-05 20:30
I have two hypotheses for this bug though:

1. It's some manifestation of Fluent's default behavior of encasing translated strings in invisible marker elements (they have something to do with text direction from memory).

**Comment by adundovi** [comment] 2022-01-05 20:32
Thanks @arctic-hen7 for looking into this. I'll try to give you a MRE soon.

**Comment by lukechu10** [comment] 2022-01-06 03:26
I believe this is because of sycamore ssr codegen. I'll take a look in this as well

**Comment by adundovi** [comment] 2022-01-06 04:57
> Even after running `perseus clean`, that reproduction in the i18n example (also removing the `<title>` element from `index.html`), doesn't produce this bug for me on Firefox 96.0b10 running on Ubuntu. Maybe there's something else going on here, could you post a self-contained MRE?

OK, what was missing is an additional string next to the translated one, such as:

```rust
#[perseus::head]
pub fn head() -> View<SsrNode> {
    view! {
         title { (t!("about")) " > Test" }
    }
}```

This reproduce the problem in a clean i18n example.

**Comment by adundovi** [comment] 2022-01-06 05:13
I've tested without the translation string:

```rust
#[perseus::head]
pub fn head() -> View<SsrNode> {
    let foo = "Foo".to_string();
    view! {
         title { (foo) " | Bar" }
    }
}
```

![image](https://user-images.githubusercontent.com/8830248/148331602-4b3c60d6-c1ec-44c8-ba48-2e09babb04c7.png)

and with it:

```rust
#[perseus::head]
pub fn head() -> View<SsrNode> {
    view! {
         title { (t!("about")) " | Bar" }
    }
}
```

![image](https://user-images.githubusercontent.com/8830248/148331767-8ba4ee5e-fd6f-43e1-bb7e-aa91d9b6cc79.png)

**Comment by adundovi** [comment] 2022-01-06 05:16
Hmm, on the other hand - the following works without the issue:

```rust
#[perseus::head]
pub fn head() -> View<SsrNode> {
    let foo = t!("about");
    view! {
         title { (foo) " | Bar" }
    }
}
```

Maybe this depends on how `view!` macro is evaluated?

**Comment by arctic-hen7** [comment] 2022-01-06 05:24
Ah I see. @lukechu10 this should be fixable by using SSR while explicitly telling Sycamore that it doesn't need to prepare for hydration (the head will never be hydrated). Is that possible?

**Comment by adundovi** [comment] 2022-01-06 05:26
Just for the record, this is the minimal issue-triggering case:

```rust
#[perseus::head]
pub fn head() -> View<SsrNode> {
    view! {
         title { ("Foo".to_string()) " | Bar" }
    }
}
```

**Comment by adundovi** [comment] 2022-01-06 05:36
> Ah I see. @lukechu10 this should be fixable by using SSR while explicitly telling Sycamore that it doesn't need to prepare for hydration (the head will never be hydrated). Is that possible?

Is this related to hydration? The issue persists even without the hydration feature in `Cargo.toml`.

**Comment by lukechu10** [comment] 2022-01-06 05:58
> Hmm, on the other hand - the following works without the issue:
> 
> ```rust
> #[perseus::head]
> pub fn head() -> View<SsrNode> {
>     let foo = t!("about");
>     view! {
>          title { (foo) " | Bar" }
>     }
> }
> ```
> 
> Maybe this depends on how `view!` macro is expanded?

The reason this works is because there is a simple heuristic in `view!` to deduce that `foo` can never be a dynamic value.

**Comment by arctic-hen7** [comment] 2022-01-06 06:27
> Is this related to hydration? The issue persists even without the hydration feature in `Cargo.toml`.

No, I read through that chain a little hastily and misunderstood how `view!` was handling this. Given this doesn't seem to be a Perseus issue, shall we transfer this to Sycamore?

**Comment by adundovi** [comment] 2022-01-06 07:36
> No, I read through that chain a little hastily and misunderstood how `view!` was handling this. Given this doesn't seem to be a Perseus issue, shall we transfer this to Sycamore?

Of course.

**Comment by arctic-hen7** [comment] 2022-01-06 21:50
By the same token, I'm also thinking that the `t!` macro might be able to somehow identify itself to Sycamore as unchanging. I'll play with this a bit...

**Comment by arctic-hen7** [comment] 2022-01-10 01:03
It doesn't look like Perseus can tell Sycamore that the `t!` macro will never be reactive, but using `format!` does work, so I'd advise using that in the general case.

Given that this seems to be solely a Sycamore issue, I'll close this.

**Closed by arctic-hen7** 2022-01-10 01:03 UTC
Labels: C-bug, A-i18n, A-templates, P-high

**Comment by lukechu10** [comment] 2022-01-10 05:34
> It doesn't look like Perseus can tell Sycamore that the `t!` macro will never be reactive, but using `format!` does work, so I'd advise using that in the general case.

`format!` works? Normally, `format!` and `t!` are treated the exact same way...

**Comment by arctic-hen7** [comment] 2022-01-10 05:37
No, putting everything inside a `format!` block instead of putting things next to each other.
